#!/bin/bash
#SBATCH --array=0-239
#SBATCH --partition=nrnb-compute
#SBATCH --mem=4GB
#SBATCH --time=00:15:00
#SBATCH --job-name=mutect2
#SBATCH --cpus-per-task=1
#SBATCH --ntasks=1
eval "$(conda shell.bash hook)"
conda activate /cellar/users/zkoch/miniconda3/envs/gatk4
module load samtools

echo "Job ID: $SLURM_JOB_ID"
echo "Job User: $SLURM_JOB_USER"
echo "Num Cores: $SLURM_JOB_CPUS_PER_NODE"
echo "Array Job ID: $SLURM_ARRAY_JOB_ID"
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"

################
# create index for jung using STAR
#srun /cellar/users/zkoch/dream/bash_scripts/create_star_index.sh

################

################
# align using STAR
# get a list of files in raw_data_dir
# raw_data_dir=/cellar/users/zkoch/dream/data/jung_2015/raw_RNA_seq
# fastq_files=($raw_data_dir/*.fastq)
# srun /cellar/users/zkoch/dream/bash_scripts/align_jung_rnaseq.sh ${fastq_files[$SLURM_ARRAY_TASK_ID]}
################

################
# # preprocess for variant calling
# file_pairs_fn=/cellar/users/zkoch/dream/data/jung_2015/sample_name_mapping_cleaned.tsv 
# # pair num is 1 greater than SLURM_ARRAY_TASK_ID
# pair_num=$(($SLURM_ARRAY_TASK_ID + 1))
# srun /cellar/users/zkoch/dream/bash_scripts/pre_process_bam_files_jung_rnaseq.sh $file_pairs_fn $pair_num
################

################
# call variants using GATK
chrom_names=(1:1000-125000000 1:125000001-248250621 2:1000-92300000 2:92300001-242193000 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22)
pair_nums=(1 2 3 4 5 6 7 8 9 10)
# pair mapping file
file_pairs_fn=/cellar/users/zkoch/dream/data/jung_2015/sample_name_mapping_cleaned.tsv 

# for values 0-230, print what chrom_name_idx and pair_num_idx would be
# for i in {0..239}; do
#     chrom_name_idx=$(($i % 24))
#     pair_num_idx=$(($i / 24))
#     # print the vlaues
#     echo "chrom_name: ${chrom_names[$chrom_name_idx]}, "pair_num:" ${pair_nums[$pair_num_idx]}"
# done
# start a job for each chromosome and pair_num combination, based on $SLURM_ARRAY_TASK_ID 
# chrom name is the SLURM_ARRAY_TASK_ID modulo 23
# pair num is the SLURM_ARRAY_TASK_ID divided by 23 and rounded up
chrom_name_idx=$(($SLURM_ARRAY_TASK_ID % 24))
pair_num_idx=$(($SLURM_ARRAY_TASK_ID / 24))
srun /cellar/users/zkoch/dream/bash_scripts/call_variants_jung_rnaseq_oneChr.sh ${chrom_names[$chrom_name_idx]} $file_pairs_fn ${pair_nums[$pair_num_idx]}
################

################
# then run /cellar/users/zkoch/dream/bash_scripts/create_mutation_matrix.sh
################